### ISSUE TITLE
Hello Service

### ISSUE THREAD

**Issue by MangoJoose** [Hack-The-Tunnels-8/hack-the-tunnels-fruit-salas#1]
Checkout: service/src/infrastructure/api/router.ts to get started.

Update the root API message to say "Hello World".

**Comment by MangoJoose** [comment]
!review

**Comment by shirleyzhan00** [comment]
Did you push your changes yet? I don't see the "Hello World" message in router.ts

**Comment by MangoJoose** [comment]
oh I didn't merge yet whoops

**Comment by rose-salt** [comment]
can you please merge so we can mark you approved?

**Comment by rose-salt** [comment]
!approve
